// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBblsdfFwMnZKwgLsVt83RgXAX6C_21U',
    appId: '1:369294421493:web:f180157b8f61745b8f84bc',
    messagingSenderId: '369294421493',
    projectId: 'chatapp-eacc3',
    authDomain: 'chatapp-eacc3.firebaseapp.com',
    storageBucket: 'chatapp-eacc3.appspot.com',
    measurementId: 'G-VWGVQ6T2HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwDNLbfvHwDIMlXBi-EV61rLVtIvd3IW8',
    appId: '1:369294421493:android:7a5e2fdddf9e63cc8f84bc',
    messagingSenderId: '369294421493',
    projectId: 'chatapp-eacc3',
    storageBucket: 'chatapp-eacc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0H8DAdt5mT3oXoU_wupJRWQYL-GN1fZE',
    appId: '1:369294421493:ios:eb20a7986e9f24fc8f84bc',
    messagingSenderId: '369294421493',
    projectId: 'chatapp-eacc3',
    storageBucket: 'chatapp-eacc3.appspot.com',
    androidClientId: '369294421493-pepkg2hqu0esb3qign7a839aujsgmqum.apps.googleusercontent.com',
    iosClientId: '369294421493-4i9q9ba05usibmn7931dcm7as73c88od.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0H8DAdt5mT3oXoU_wupJRWQYL-GN1fZE',
    appId: '1:369294421493:ios:a9185af2e73256128f84bc',
    messagingSenderId: '369294421493',
    projectId: 'chatapp-eacc3',
    storageBucket: 'chatapp-eacc3.appspot.com',
    androidClientId: '369294421493-pepkg2hqu0esb3qign7a839aujsgmqum.apps.googleusercontent.com',
    iosClientId: '369294421493-i6jr9n47hj6es8og9om0el8ftpio6i45.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
